### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Sirui-Xu** [Juzezhang/NeuralDome_Toolbox#1]
Hi,

Nice work! I tried to visualize the mocap data but I found the human and object dynamics are not well aligned. I noticed the use of "from models.body_models_easymocap.smplx import SMPLHModel", which, due to the incomplete codebase, appears to be non-executable on my end. I wonder if there are any modifications or a particular version of the SMPLH model that you are employing that differs from the standard, publicly available version? Or, could you guide me to generate the correct interactions?

Thank you for your time and assistance in advance.

Best

**Comment by Juzezhang** [comment]
Dear @Sirui-Xu ,

Thank you for pointing this issue out. Exactly, we utilized the SMPLH model provided by the Easymocap repositories, and it appears that the version I uploaded was missing a crucial module. My sincerest apologies for this oversight. I have now uploaded the latest version for your convenience. Additionally, due to the limitations imposed by the Firewall of China, the process of uploading my full dataset has been exceedingly slow. I anticipate that it will take another week to complete the upload. Thank you once again for your interest and patience.

Please let us know if you have any questions or require any assistance accessing the uploaded files.

Best Regards,

Juze

**Comment by Sirui-Xu** [comment]
Dear Juze,

Thank you very much for your prompt response and help!

Best,
Sirui
