### ISSUE TITLE
Is there any alternative channel to download the dataset?

### ISSUE THREAD

**Issue by Golden-Pigeon** [Juzezhang/NeuralDome_Toolbox#5]
Hi Juzezhang, thanks for your great work for the open source community. 

When I am trying to download the HOI-M3 dataset, I find that there only provides google cloud drive for downloading. However, I am now in Mainland China, which means it is difficult and costly for me to download the dataset directly. Is there any other channel to download the dataset, for example, Baidu Netdisk?

Looking forward to your reply!

Many thanks!

**Comment by Juzezhang** [comment]
Hi  @Golden-Pigeon ,

Thank you for reaching out. Unfortunately, this project no longer has any funding support. The current Google Drive is personally paid for by Jingyan  @zhanglele12138  and me, and we can not provide additional options like Baidu Netdisk at the moment due to the monthly membership costs. I apologize for any inconvenience this may cause.

Best regards,
Juze Zhang

**Comment by Golden-Pigeon** [comment]
Thanks for your quick reply!

I will find other approachs to download the dataset.
